# SPDX-FileCopyrightText: 2026 Steve Prud'Homme and GNU TrackGenerator contributors
# SPDX-License-Identifier: GPL-3.0-only

"""Generation engine for GNU TrackGenerator.

The GUI calls this module, but this module never imports the GUI.  It owns the
local generation pipeline:

1. Save .gen project JSON.
2. Generate .ly LilyPond source.
3. Run LilyPond through subprocess to produce MIDI.
4. Run FluidSynth or TiMidity through subprocess to produce WAV.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from .models import APP_NAME, APP_VERSION, ProjectData, Segment, ValidationError
from .project_io import save_project


class GenerationError(RuntimeError):
    """Raised when a subprocess or external dependency fails."""


@dataclass(frozen=True)
class GenerationResult:
    """Paths created by one successful generation run."""

    gen_path: Path
    lilypond_path: Path
    midi_path: Path
    wav_path: Path


def _safe_stem(name: str) -> str:
    """Return a filesystem-friendly file stem."""
    cleaned = "".join(char if char.isalnum() or char in "-_" else "_" for char in name.strip())
    return cleaned or "gnu_trackgenerator_click"


def _require_executable(binary_name: str) -> str:
    """Return the executable path or raise a helpful error."""
    executable = shutil.which(binary_name)
    if not executable:
        raise GenerationError(
            f"Impossible de trouver '{binary_name}' sur le PATH de l'OS. "
            "Installez l'outil ou ajoutez-le au PATH avant de générer."
        )
    return executable


def _run_command(command: list[str], cwd: Path) -> None:
    """Run a command and convert subprocess failures into GenerationError."""
    try:
        completed = subprocess.run(
            command,
            cwd=str(cwd),
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError as exc:
        raise GenerationError(f"Commande introuvable: {command[0]}") from exc
    except subprocess.CalledProcessError as exc:
        stdout = exc.stdout.strip()
        stderr = exc.stderr.strip()
        details = "\n".join(part for part in [stdout, stderr] if part)
        raise GenerationError(
            f"La commande a échoué: {' '.join(command)}\n{details}"
        ) from exc

    # LilyPond and audio tools sometimes report useful warnings on stderr even
    # when the command succeeds.  We intentionally do not treat warnings as errors.
    _ = completed


def _segment_measure_pattern(segment: Segment) -> str:
    """Build one measure of click-track drum notes for a segment.

    Rule required by the specification:
    - first subdivision: bass drum, LilyPond abbreviated name `bd`
    - all other subdivisions: snare, LilyPond abbreviated name `sn`
    """
    duration = str(segment.denominator)
    notes = [f"bd{duration}"]
    notes.extend(f"sn{duration}" for _ in range(segment.numerator - 1))
    return " ".join(notes)


def build_lilypond_source(project: ProjectData, title: str = APP_NAME) -> str:
    """Generate the full LilyPond source for a project."""
    project.validate()

    music_lines: list[str] = []
    for index, segment in enumerate(project.segments, start=1):
        pattern = _segment_measure_pattern(segment)
        music_lines.extend(
            [
                f"  % Segment {index}: {segment.numerator}/{segment.denominator}, "
                f"{segment.bpm} BPM, {segment.measures} mesure(s)",
                f"  \\time {segment.numerator}/{segment.denominator}",
                # In v0.1.0, BPM is interpreted on the denominator beat unit.
                # Example: 7/8 at 120 => eighth-note = 120.
                f"  \\tempo {segment.denominator} = {segment.bpm}",
                f"  \\repeat unfold {segment.measures} {{ {pattern} | }}",
                "",
            ]
        )

    music = "\n".join(music_lines).rstrip()

    return f'''% Auto-generated by {APP_NAME} {APP_VERSION}
% Do not edit this file manually unless you know what you are doing.

\\version "2.24.0"

\\header {{
  title = "{title}"
  composer = "{APP_NAME}"
  tagline = "Generated with {APP_NAME} {APP_VERSION}"
}}

clickTrack = \\drummode {{
{music}
}}

\\score {{
  \\new DrumStaff \\with {{
    instrumentName = "Click"
  }} {{
    \\clickTrack
  }}
  \\layout {{ }}
  \\midi {{ }}
}}
'''


def write_lilypond_file(project: ProjectData, path: str | Path, title: str = APP_NAME) -> Path:
    """Write a .ly file and return its path."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(build_lilypond_source(project, title=title), encoding="utf-8")
    return target


def compile_lilypond_to_midi(
    lilypond_path: str | Path,
    output_stem: str | Path,
    lilypond_binary: str = "lilypond",
) -> Path:
    """Compile a LilyPond file to MIDI and return the .mid path.

    LilyPond commonly writes `.midi`.  The application normalizes the result to
    `.mid` because the user-facing specification asks for a .mid file.
    """
    lilypond_executable = _require_executable(lilypond_binary)
    ly_path = Path(lilypond_path)
    stem = Path(output_stem)
    stem.parent.mkdir(parents=True, exist_ok=True)

    command = [
        lilypond_executable,
        "-dno-point-and-click",
        "-o",
        str(stem),
        str(ly_path),
    ]
    _run_command(command, cwd=stem.parent)

    midi_candidates = [stem.with_suffix(".midi"), stem.with_suffix(".mid")]
    produced = next((candidate for candidate in midi_candidates if candidate.exists()), None)
    if produced is None:
        raise GenerationError("LilyPond a terminé sans produire de fichier MIDI attendu.")

    normalized = stem.with_suffix(".mid")
    if produced != normalized:
        if normalized.exists():
            normalized.unlink()
        produced.rename(normalized)
    return normalized


def render_midi_to_wav(
    midi_path: str | Path,
    wav_path: str | Path,
    soundfont_path: str | Path | None = None,
    prefer: str = "fluidsynth",
) -> Path:
    """Render MIDI to WAV using FluidSynth, with TiMidity as fallback.

    FluidSynth generally needs a SoundFont (.sf2 or .sf3).  The path can come
    from the GUI, the .gen file, or the TRACKGENERATOR_SOUNDFONT environment
    variable.  TiMidity can work if it is installed and configured system-wide.
    """
    midi = Path(midi_path)
    wav = Path(wav_path)
    wav.parent.mkdir(parents=True, exist_ok=True)

    env_soundfont = os.environ.get("TRACKGENERATOR_SOUNDFONT")
    sf2 = Path(soundfont_path or env_soundfont) if (soundfont_path or env_soundfont) else None

    fluidsynth = shutil.which("fluidsynth")
    timidity = shutil.which("timidity")

    use_fluidsynth_first = prefer.lower() == "fluidsynth"
    tools = ["fluidsynth", "timidity"] if use_fluidsynth_first else ["timidity", "fluidsynth"]

    last_error: GenerationError | None = None
    for tool in tools:
        if tool == "fluidsynth" and fluidsynth:
            if not sf2 or not sf2.exists():
                last_error = GenerationError(
                    "FluidSynth est installé, mais aucun SoundFont valide (.sf2/.sf3) n'a été fourni. "
                    "Sélectionnez un SoundFont dans l'interface ou définissez TRACKGENERATOR_SOUNDFONT."
                )
                continue
            command = [
                fluidsynth,
                "-ni",
                "-T",
                "wav",
                "-F",
                str(wav),
                str(sf2),
                str(midi),
            ]
            _run_command(command, cwd=wav.parent)
            return wav

        if tool == "timidity" and timidity:
            command = [timidity, str(midi), "-Ow", "-o", str(wav)]
            _run_command(command, cwd=wav.parent)
            return wav

    if last_error:
        raise last_error
    raise GenerationError(
        "Aucun moteur MIDI -> WAV trouvé. Installez FluidSynth ou TiMidity."
    )


def generate_project(
    project: ProjectData,
    output_dir: str | Path,
    base_name: str = "gnu_trackgenerator_click",
    lilypond_binary: str = "lilypond",
) -> GenerationResult:
    """Run the complete local generation pipeline."""
    project.validate()
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = out_dir / _safe_stem(base_name)

    gen_path = save_project(project, stem.with_suffix(".gen"))
    ly_path = write_lilypond_file(project, stem.with_suffix(".ly"), title=stem.name)
    midi_path = compile_lilypond_to_midi(ly_path, stem, lilypond_binary=lilypond_binary)
    wav_path = render_midi_to_wav(
        midi_path,
        stem.with_suffix(".wav"),
        soundfont_path=project.soundfont_path,
    )
    return GenerationResult(
        gen_path=gen_path,
        lilypond_path=ly_path,
        midi_path=midi_path,
        wav_path=wav_path,
    )
